### PR TITLE
Make it work on OpenCL :-)

### PR DESCRIPTION
**Pull request by hughperkins**
Hi Karpathy,

This pull request allows train.lua to run on OpenCL.

Use it as follows:

```
th train.lua -data_dir data/tinyshakespeare -opencl 1
```

(You'll need to install [cltorch](https://github.com/hughperkins/cltorch) and [clnn](https://github.com/hughperkins/clnn) first of course :-) )

### CODE REVIEW

**Comment by soumith** [comment]
verynice!!!

**Comment by karpathy** [comment]
Neat, thank you!

**Comment by hughperkins** [comment]
Hmmmm, you know what, I might not have quite tested this yet :-P  I thought I had tested it, but it was 12pm, and in the cold light of morning, I see a message about 'cltorch not available, falling back on cpu', and when I fix that... it crashes :-P  So, I dont think there are any huge conceptual missing bits, but there might be one or two buggettes I need to fix first :-P

**Comment by hughperkins** [comment]
Ok, seems it trains now.  not very speedy yet :-/

```
using OpenCL on GPU 0...
exists	data/tinyshakespeare/vocab.t7
loading data files...
cutting off end of data so that the batches/sequences divide evenly
reshaping tensor...
data load done. Number of data batches in train: 423, val: 23, test: 0
vocab size: 65
exists	cv
creating an LSTM with 2 layers
Using NVIDIA Corporation platform: NVIDIA CUDA
Using device: GeForce 940M
[New Thread 0x7ffff1758700 (LWP 7057)]
[New Thread 0x7ffff3f59700 (LWP 7058)]
[New Thread 0x7ffff475a700 (LWP 7059)]
[New Thread 0x7fffe1b21700 (LWP 7060)]
[New Thread 0x7fffe1320700 (LWP 7061)]
[New Thread 0x7fffe0b1f700 (LWP 7062)]
number of parameters in the model: 240321
cloning rnn
cloning criterion
1/21150 (epoch 0.002), train_loss = 4.19702585, grad/param norm = 4.6079e-01, time/batch = 2.57s
2/21150 (epoch 0.005), train_loss = 4.10388269, grad/param norm = 5.6379e-01, time/batch = 2.14s
3/21150 (epoch 0.007), train_loss = 3.68858851, grad/param norm = 1.5368e+00, time/batch = 2.15s
4/21150 (epoch 0.009), train_loss = 3.53069218, grad/param norm = 2.2024e+00, time/batch = 2.13s
5/21150 (epoch 0.012), train_loss = 3.34717288, grad/param norm = 9.6783e-01, time/batch = 2.14s
6/21150 (epoch 0.014), train_loss = 3.36614721, grad/param norm = 5.2350e-01, time/batch = 2.12s
7/21150 (epoch 0.017), train_loss = 3.34456545, grad/param norm = 3.1590e-01, time/batch = 2.13s
8/21150 (epoch 0.019), train_loss = 3.31248548, grad/param norm = 4.3439e-01, time/batch = 2.14s
```

**Comment by karpathy** [comment]
Please send pull request if there are remaining bugs

**Comment by hughperkins** [comment]
Ok, it runs only 3 times slower than CUDA now, on the same hardware.  No new PR required, since all the changes are in the underlying [cltorch](https://github.com/hughperkins/cltorch).

**Comment by hughperkins** [comment]
For info, updates to cltorch just now change time on NVIDIA 940M from 0.52seconds to 0.27seconds, which is only 2 times slower than CUDA now.  On AMD hardware, the speedup is three times faster compared to before, but still some work to be done.

**Pull request merged**
