### PR TITLE
Handle large input data files by reading smaller chunks

### PR DESCRIPTION
**Pull request by ananda621**
Load input files chunk by chunk to handle files that are larger than 1GB for which reading whole file will cause luajit to exit with message `not enough memory`.

Tested to work with data/tinyshakespeare/ and other datasets.

### CODE REVIEW

**Comment by hughperkins** [comment]
Nice! :-)

**Comment by karpathy** [comment]
Hi thanks this looks nice! Sorry for paranoia but did you test that this gives identical results for e.g. tinyshakespear? As in the ByteTensors are exactly equal in size and content?

**Comment by ananda621** [comment]
Yes. Here are the md5sums:

Original version:
`mpro:~/studio/karpathy/char-rnn$ md5 data/tinyshakespeare/*.t7
MD5 (data/tinyshakespeare/data.t7) = 8b57c73a06f867c61de13711af34bfcf
MD5 (data/tinyshakespeare/vocab.t7) = cba2fc2cf3b5e36ec91fc9d0ca6b390d`

Pull requested version:
`mpro:~/studio/char-rnn$ md5 data/tinyshakespeare/*.t7
MD5 (data/tinyshakespeare/data.t7) = 8b57c73a06f867c61de13711af34bfcf
MD5 (data/tinyshakespeare/vocab.t7) = cba2fc2cf3b5e36ec91fc9d0ca6b390d`

**Comment by karpathy** [comment]
awesome, thank you for running the test and reporting back!

**Pull request merged**
