### PR TITLE
Updated readme for opencl usage

### PR DESCRIPTION
**Pull request by hughperkins**
Hi Karpathy,

This PR updates the readme for OpenCL usage.

### CODE REVIEW

**Comment by karpathy** [comment]
I'd be happy to merge this, but first - have the issues that came up before been resolved? Do the opencl parts work? I Don't have an ATI card so I'm relying on you to run all the reasonable tests and make sure things are working properly :)

**Comment by hughperkins** [comment]
Haha, once bitten, twice shy :-D

And you are right, I think there are a few test that I should do:
1. does it run?  (Yes, pass)
2. does the training error decrease (Yes, pass, at least for 10 batches or so; havent tried for longer :-P)
3. is performance kind of ok (Yes, pass-ish.  Ideally I'd like it to be no more than twice as slow as CUDA, and 3 times as slow is a bit border-line, but kind of ok-ish perhaps?)
4. does it start quoting Shakespeare at me? => I probably need to check this, and get back to you on this last point

**Comment by culurciello** [comment]
Hi Hugh, it is quite nice you got this to work in OpenCL within 3x from CUDA. How about using CPU only? What is the difference there?

**Comment by hughperkins** [comment]
Hi cuiurciello,

Per https://github.com/hughperkins/clnn, you can see the per-batch timings are:
- cpu: 3.4s
- clnn: 0.52s
- cunn: 0.13s

This is using an NVidia 940M graphics card, and an Intel i5-5200U processor.

**Pull request merged**
