### PR TITLE
adding torch/nn to dependencies

### PR DESCRIPTION
**Pull request by ajkl**

### CODE REVIEW

**Comment by karpathy** [comment]
Oops, doesn't `nn` come with Torch by default? I can't remember now.

**Comment by ajkl** [comment]
I am not sure either. Probably a version mismatch as Soumith mentioned. Dont have much experience with torch, but `luarocks install nn` clearly solves https://github.com/karpathy/char-rnn/issues/76 for me. Maybe this can be added in Notes section and not in the dependencies section of the README ? Let me know I can modify the PR.

**Comment by karpathy** [comment]
I think you had `nn` but somehow an older version of it, and when you installed it was updated? Hmmmm

**Comment by ajkl** [comment]
Correct. And I had just installed torch for the first time before doing all this. So I was assuming nn will already be on latest version. I guess I was wrong.

**Comment by karpathy** [comment]
alright, can't hurt :) thanks!

**Pull request merged**
