### PR TITLE
Add scoring script

### PR DESCRIPTION
**Pull request by ryaneleary**
This script accepts newline separated sequences and outputs a log-probability of each sequence. Addresses #59.

### CODE REVIEW

**Comment by karpathy** [comment]
Thank you, I think I am going to leave this out of the master repo because it leads to more code duplication, repo clutter, and I think does not correspond to a very common use case.

**Comment by ryaneleary** [comment]
There's certainly a decent amount of code duplication. I'm happy to try to make it more modular (across the train and sample scripts as well). But if you feel it's not a useful addition, I'll just close the PR.

**Comment by karpathy** [comment]
It's probably a fairly constrained use case. Thanks for the pull request though, I encourage future ones if there are improvements to the core functionality! 

If some other people request this functionality we can try revive it.

Cheers,
Andrej

**Comment by JohnReid** [comment]
I'd like to see this. Thanks, John.

**Pull request closed without merging**
